config/urls.py
from django.contrib import admin
from django.urls import path, include
from guide import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('guide/', include('guide.urls')), #guide/로 시작되는 페이지 요청은 모두 guide.urls.py 파일에 있는 URL 매핑을 참고하여 처리하라는 의미
]

guide/urls.py
from django.urls import path

from . import views

app_name='guide'

urlpatterns = [
    path('', views.index, name='index'),

    path('select/', views.baseAlchohol, name='base'),

    path('how/', views.how, name='how'),

    #vodka 영역
    path('vodka/', views.vodka, name='vodka'),
    path('vodka/orange/', views.v_orange, name='v_orange'),
    path('vodka/orange/ice_result', views.voi_result, name='v_o_ice_result'),
    path('vodka/orange/grenadine_result', views.vog_result, name='v_o_grenadine_result'),

    path('vodka/cranberry/', views.v_cranberry, name='v_cranberry'),
    path('vodka/cranberry/lime_result', views.vcl_result, name='v_c_lime_result'),
    path('vodka/cranberry/grapefruit_result', views.vcg_result, name='v_c_grapefruit_result'),
    path('vodka/cranberry/limejuice_result', views.vclj_result, name='v_c_limejuice_result'),
    path('vodka/cranberry/orangejuice_result', views.vco_result, name='v_c_orangejuice_result'),

    path('vodka/limejuice_result', views.vlj_result, name='v_limejuice_result'),
    path('vodka/cola_result', views.vc_result, name='v_cola_result'),

    path('vodka/tonic/', views.v_tonic, name='v_tonic'),
    path('vodka/tonic/lime_result', views.vtl_result, name='v_t_lime_result'),

    path('vodka/gingerbeer/', views.v_gingerbeer, name='v_gingerbeer'),
    path('vodka/gingerbeer/lime_result', views.vgl_result, name='v_g_lime_result'),


    #path('vodka/cranberry/', views.v_c_add, name='cranberry'),
    path('rum/', views.rum, name='rum'),
    path('rum/orange/', views.r_orange, name='r_orange'),
    path('rum/orange/ice_result', views.roi_result, name='r_o_ice_result'),

    path('rum/cola/', views.r_cola, name='r_cola'),
    path('rum/cola/lime_result', views.rcl_result, name='r_c_lime_result'),

    path('rum/water', views.r_water, name='r_water'),
    path('rum/water/sugar_result', views.rws_result, name='r_w_sugar_result'),

    path('rum/limejuice/', views.r_limejuice, name='r_limejuice'),
    path('rum/limejuice/sugar_result', views.rls_result, name='r_l_sugar_result'),

    path('rum/gingerbeer/', views.rg_result, name='r_g_result'),

    path('rum/pineapple/', views.r_pineapple, name='r_pineapple'),
    path('rum/pineapple/coconut_result/', views.rpc_result, name='r_p_coconut_result'),

    path('gin/', views.gin, name='gin'),
    path('gin/limejuice/', views.g_limejuice, name='g_limejuice'),
    path('gin/limejuice/sugar_result/', views.gls_result, name='g_l_sugar_result'),
    path('gin/limejuice/sparkling_result/', views.glsp_result, name='g_l_sparkling_result'),
    path('gin/limejuice/cider_result/', views.glc_result, name='g_l_cider_result'),
    path('gin/limejuice/tonic_result/', views.glt_result, name='g_l_tonic_result'),

    path('gin/grapefruit/', views.ggf_result, name='ggf_result'),

    path('gin/gingerbeer/', views.g_gingerbeer, name='g_gingerbeer'),
    path('gin/gingerbeer/sparkling_result/', views.ggs_result, name='g_g_sparkling_result'),

    path('whisky/', views.whisky, name='whisky'),
    path('whisky/coffee/', views.w_coffee, name='w_coffee'),
    path('whisky/coffee/whipping_result/', views.wcw_result, name='w_c_whipping_result'),

    path('whisky/sparkling/', views.w_sparkling, name='w_sparkling'),
    path('whisky/sparkling/sugar_result/', views.wss_result, name='w_s_sugar_result'),

    path('whisky/cola_result/', views.wc_result, name='wc_result'),

    path('tequila/', views.tequila, name='tequila'),
    path('tequila/orangejuice/', views.t_orangejuice, name='t_orangejuice'),
    path('tequila/orangejuice/grenadine_result', views.tog_result, name='t_o_grenadine_result'),

    path('tequila/lemonjuice/', views.t_lemonjuice, name='t_lemonjuice'),
    path('tequila/lemonjuice/pineapple_result', views.tlp_result, name='t_l_pineapple_result'),
    path('tequila/lemonjuice/sugar_result', views.tls_result, name='t_l_sugar_result'),

    path('tequila/limejuice/', views.t_limejuice, name='t_limejuice'),
    path('tequila/limejuice/grenadine_result/', views.tlg_result, name='t_l_grenadine_result'),
    path('tequila/limejuice/cola_result/', views.tlc_result, name='t_l_cola_result'),

    path('non/', views.non, name='non'),
    path('non/lemonade/', views.n_lemonade, name='n_lemonade'),
    path('non/lemonade/orange/', views.n_l_orange, name='n_l_orange'),
    path('non/lemonade/orange/pineapple_result/', views.nlop_result, name='n_l_o_pineapple_result'),
    path('non/lemonade/eggwhite/', views.n_l_eggwhite, name='n_l_eggwhite'),
    path('non/lemonade/eggwhite/sugar_result/', views.nles_result, name='n_l_e_sugar_result'),

    path('non/grenadine/', views.n_grenadine, name='n_grenadine'),
    path('non/grenadine/gingerbeer_result/', views.ngg_result, name='n_g_gingerbeer_result'),
    path('non/grenadine/orange_result/', views.ngo_result, name='n_g_orange_result'),

    path('non/limejuice/', views.n_limejuice, name='n_limejuice'),
    path('non/limejuice/sparkling/', views.n_l_sparkling, name='n_l_sparkling'),
    path('non/limejuice/sparkling/sugar_result/', views.nlss_result, name='n_l_s_sugar_result'),

    path('info/', views.info, name='info'),
    path('info/tool/', views.tool, name='tool'),
    path('info/term/', views.term, name='term'),
    path('info/source/', views.source, name='source'),
]

guide/models.py
from django.db import models

# class baseAlchohol(models.Model):
#     img = models.ImageField()
#     name = models.CharField(max_length = 10)
#
# class supportAlchohol(models.Model):
#     img = models.ImageField()
#     name = models.CharField(max_length = 10)
#
# class additives(models.Model):
#     img = models.ImageField()
#     name = models.CharField(max_length = 10)
#
# class result(models.Model):
#     img = models.ImageField()
#     name = models.CharField(max_length = 10)
#     desc = models.TextField()
#

guide/views.py
from django.shortcuts import render
from django.http import HttpResponse
#from .models import baseAlchohol
from django.shortcuts import render

def index(request):
    """
    시작화면
    """

    baseAlchol = {"vodka": 0, "rum": 1}
    return render(request, 'guide/main_menu.html')
    #return HttpResponse("안녕하세요. 홈텐딩 길라잡이에 오신것을 환영합니다.")

def baseAlchohol(request):
    """
    기주 목록 출력
    """
    baseAlchol = {"vodka": 0, "rum": 1}
    return render(request, 'guide/baseAlchohol_list.html')

def vodka(request):
    """
    support_vodka 목록 출력
    """
    return render(request, 'guide/support/vodka.html')

def v_orange(request):
    """
    v_orange 목록 출력
    """
    return render(request, 'guide/additives/v_orange.html')

def voi_result(request):
    """
    결과 화면 출력
    """
    return render(request, 'guide/result/voiResult.html')

def vog_result(request):
    """
    결과 화면 출력
    """
    return render(request, 'guide/result/vogResult.html')

def v_cranberry(request):
    """
    v_orange 목록 출력
    """
    return render(request, 'guide/additives/v_cranberry.html')

def vcl_result(request):
    """
    결과 화면 출력
    """
    return render(request, 'guide/result/vclResult.html')

def vcg_result(request):
    """
    결과 화면 출력
    """
    return render(request, 'guide/result/vcgResult.html')

def vclj_result(request):
    """
    결과 화면 출력
    """
    return render(request, 'guide/result/vcljResult.html')

def vco_result(request):
    """
    결과 화면 출력
    """
    return render(request, 'guide/result/vcoResult.html')

def vlj_result(request):
    """
    v_limejuice 목록 출력
    """
    return render(request, 'guide/result/vljResult.html')

def v_tonic(request):
    """
    v_tonic 목록 출력
    """
    return render(request, 'guide/additives/v_tonic.html')

def vtl_result(request):
    """
    결과 화면 출력
    """
    return render(request, 'guide/result/vtlResult.html')

def v_gingerbeer(request):
    """
    v_tonic 목록 출력
    """
    return render(request, 'guide/additives/v_gingerbeer.html')

def vgl_result(request):
    """
    결과 화면 출력
    """
    return render(request, 'guide/result/vglResult.html')

def vc_result(request):
    """
    결과 화면 출력
    """
    return render(request, 'guide/result/vcResult.html')

def rum(request):
    """
    rum 목록 출력
    """
    return render(request, 'guide/support/rum.html')

def r_orange(request):
    """
    r_orange 목록 출력
    """
    return render(request, 'guide/additives/r_orange.html')

def roi_result(request):
    """
    r_orange 목록 출력
    """
    return render(request, 'guide/result/roiResult.html')

def r_cola(request):
    """
    r_orange 목록 출력
    """
    return render(request, 'guide/additives/r_cola.html')

def rcl_result(request):
    """
    r_orange 목록 출력
    """
    return render(request, 'guide/result/rclResult.html')

def rcl_result(request):
    """
    r_orange 목록 출력
    """
    return render(request, 'guide/result/rclResult.html')

def r_water(request):
    """
    r_orange 목록 출력
    """
    return render(request, 'guide/additives/r_water.html')

def rws_result(request):
    """
    r_orange 목록 출력
    """
    return render(request, 'guide/result/rwsResult.html')

def r_limejuice(request):
    """
    r_orange 목록 출력
    """
    return render(request, 'guide/additives/r_limejuice.html')

def rls_result(request):
    """
    r_orange 목록 출력
    """
    return render(request, 'guide/result/rlsResult.html')

def rg_result(request):
    """
    r_orange 목록 출력
    """
    return render(request, 'guide/result/rgResult.html')

def r_pineapple(request):
    """
    r_orange 목록 출력
    """
    return render(request, 'guide/additives/r_pineapple.html')

def rpc_result(request):
    """
    r_orange 목록 출력
    """
    return render(request, 'guide/result/rpcResult.html')

def gin(request):
    """
    support_vodka 목록 출력
    """
    return render(request, 'guide/support/gin.html')

def g_limejuice(request):
    """
    g_limejuice 목록 출력
    """
    return render(request, 'guide/additives/g_limejuice.html')

def gls_result(request):
    """
    g_limejuice 목록 출력
    """
    return render(request, 'guide/result/glsResult.html')

def glsp_result(request):
    """
    g_limejuice 목록 출력
    """
    return render(request, 'guide/result/glspResult.html')

def glc_result(request):
    """
    g_limejuice 목록 출력
    """
    return render(request, 'guide/result/glcResult.html')

def glt_result(request):
    """
    g_limejuice 목록 출력
    """
    return render(request, 'guide/result/gltResult.html')

def ggf_result(request):
    """
    g_limejuice 목록 출력
    """
    return render(request, 'guide/result/ggfResult.html')

def g_gingerbeer(request):
    """
    g_limejuice 목록 출력
    """
    return render(request, 'guide/additives/g_gingerbeer.html')

def ggs_result(request):
    """
    g_limejuice 목록 출력
    """
    return render(request, 'guide/result/ggsResult.html')

def whisky(request):
    """
    whisky 목록 출력
    """
    return render(request, 'guide/support/whisky.html')

def w_coffee(request):
    """
    g_limejuice 목록 출력
    """
    return render(request, 'guide/additives/w_coffee.html')

def wcw_result(request):
    """
    g_limejuice 목록 출력
    """
    return render(request, 'guide/result/wcwResult.html')

def w_sparkling(request):
    """
    g_limejuice 목록 출력
    """
    return render(request, 'guide/additives/w_sparkling.html')

def wss_result(request):
    """
    g_limejuice 목록 출력
    """
    return render(request, 'guide/result/wssResult.html')

def wc_result(request):
    """
    g_limejuice 목록 출력
    """
    return render(request, 'guide/result/wcResult.html')

def tequila(request):
    """
    whisky 목록 출력
    """
    return render(request, 'guide/support/tequila.html')

def t_orangejuice(request):
    """
    g_limejuice 목록 출력
    """
    return render(request, 'guide/additives/t_orangejuice.html')

def tog_result(request):
    """
    g_limejuice 목록 출력
    """
    return render(request, 'guide/result/togResult.html')

def t_lemonjuice(request):
    """
    g_limejuice 목록 출력
    """
    return render(request, 'guide/additives/t_lemonjuice.html')

def tlp_result(request):
    """
    g_limejuice 목록 출력
    """
    return render(request, 'guide/result/tlpResult.html')

def tls_result(request):
    """
    g_limejuice 목록 출력
    """
    return render(request, 'guide/result/tlsResult.html')

def t_limejuice(request):
    """
    g_limejuice 목록 출력
    """
    return render(request, 'guide/additives/t_limejuice.html')

def tlg_result(request):
    """
    g_limejuice 목록 출력
    """
    return render(request, 'guide/result/tlgResult.html')

def tlc_result(request):
    """
    g_limejuice 목록 출력
    """
    return render(request, 'guide/result/tlcResult.html')

def non(request):
    """
    whisky 목록 출력
    """
    return render(request, 'guide/support/non.html')

def n_lemonade(request):
    """
    g_limejuice 목록 출력
    """
    return render(request, 'guide/additives/n_lemonade.html')

def n_l_orange(request):
    """
    g_limejuice 목록 출력
    """
    return render(request, 'guide/additives/n_l_orange.html')

def nlop_result(request):
    """
    g_limejuice 목록 출력
    """
    return render(request, 'guide/result/nlopResult.html')

def n_l_eggwhite(request):
    """
    g_limejuice 목록 출력
    """
    return render(request, 'guide/additives/n_l_eggwhite.html')

def nles_result(request):
    """
    g_limejuice 목록 출력
    """
    return render(request, 'guide/result/nlesResult.html')

def n_grenadine(request):
    """
    g_limejuice 목록 출력
    """
    return render(request, 'guide/additives/n_grenadine.html')

def ngg_result(request):
    """
    g_limejuice 목록 출력
    """
    return render(request, 'guide/result/nggResult.html')

def ngo_result(request):
    """
    g_limejuice 목록 출력
    """
    return render(request, 'guide/result/ngoResult.html')

def n_limejuice(request):
    """
    g_limejuice 목록 출력
    """
    return render(request, 'guide/additives/n_limejuice.html')

def n_l_sparkling(request):
    """
    g_limejuice 목록 출력
    """
    return render(request, 'guide/additives/n_l_sparkling.html')

def nlss_result(request):
    """
    g_limejuice 목록 출력
    """
    return render(request, 'guide/result/nlssResult.html')

def how(request):
    """
    설명화면
    """
    return render(request, 'guide/how.html')

def info(request):
    """
    설명화면
    """
    return render(request, 'guide/otherInfo.html')

def tool(request):
    """
    설명화면
    """
    return render(request, 'guide/Info/tool.html')

def term(request):
    """
    설명화면
    """
    return render(request, 'guide/Info/term.html')

def source(request):
    """
    설명화면
    """
    return render(request, 'guide/Info/source.html')

templates/guide/baseAlchohol_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<p style="font-size:18px; color:white;" align="center">베이스로 삼고 싶은 술을 골라주세요</p>
<div class="container my-3">
        <table class="table">
                <tr>
                        <td>
                                <button type="button" onclick="location.href='{% url 'guide:vodka' %}'">
                                <img src="{% static 'img/vodka2.jpg' %}" style="display:block;">보드카
                                </button>
                        </td>
                        <td>
                                <button type="button" onclick="location.href='{% url 'guide:rum' %}'">
                                <img src="{% static 'img/rum2.jpg' %}" style="display:block;">럼
                                </button>
                        </td>
                        <td>
                                <button type="button" onclick="location.href='{% url 'guide:tequila' %}'">
                                <img src="{% static 'img/tequila.jpeg' %}" style="display:block;">테킬라
                                </button>
                        </td>
                </tr>
                <tr>
                        <td>
                                <button type="button" onclick="location.href='{% url 'guide:gin' %}'">
                                <img src="{% static 'img/gin.jpg' %}" style="display:block;">진
                                </button>
                        </td>
                        <td>
                                <button type="button" onclick="location.href='{% url 'guide:whisky' %}'">
                                <img src="{% static 'img/whisky.jpg' %}" style="display:block;">위스키
                                </button>
                        </td>
                        <td>
                                <button type="button" onclick="location.href='{% url 'guide:non' %}'">
                                <img src="{% static 'img/nonalcohol.jpg' %}" style="display:block;">논알콜 칵테일
                                </button>
                        </td>
                </tr>
        </table>
</div>

{% endblock %}

templates/guide/how.html
{% extends 'howToUse.html' %}
{% load static %}
{% block content %}
<h3>활용가이드(How to use)</h3>
<div class="container my-3">
        <div style="background-color:#ffffff; color:#000000;">
                <p style="font-size:18px;">&nbsp 홈텐딩 길라잡이는 집에 있거나 구하기 쉬운 재료들로 구성한 칵테일만을 선정해 마치 길을 찾는 것처럼 이미 소지하고 있는 재료들 혹은 넣어보고 싶은 재료들을 선택해 그에 맞는 칵테일의 명칭과 제조 방법을 알기 쉽게 알려주는 웹 페이지입니다.</p>
                <p style="font-size:18px;">&nbsp 칵테일에 필요한 기주(베이스로 삼을 술)들과, 각종 과일들을(라임, 오렌지, 레몬) 구비해 두시고, 모든 칵테일은 얼음을 필요로 하니 이 역시 준비해 두신다면 이 웹페이지에 나오는 거의 대부분의 칵테일을 제조할 수 있습니다.</p>
                <table>
                        <tr>
                                <td>
                                        <img src="{% static 'img/desc1.png' %}" style="display:block;">
                                </td>
                        </tr>
                        <tr>
                                <td>
                                        <img src="{% static 'img/desc2.png' %}" style="display:block;">
                                </td>
                        </tr>
                        <tr>
                                <td>
                                        <img src="{% static 'img/otherinfo_screen.png' %}" style="display:block;">
                                </td>
                        </tr>
                </table>
        </div>
</div>
{% endblock %}

templates/guide/main_menu.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h3>홈텐딩 길라잡이에 오신것을 환영합니다.</h3>
<div class="container my-3">
        <div>
                <div style="font-size:18px; color:white;" align="center">
                        <p>홈텐딩 길라잡이는 집에 있는 재료들로 만들수 있는 칵테일 제조법을 알려주는 사이트입니다.</p>
                        <p>처음 방문하신 분이라면 "길라잡이 활용하기" 페이지에서 이용방법을 확인하시는 것을 권장합니다.</p>
                </div>
        <table class="table">
                <tr align="center">
                        <td>
                                <button type="button" onclick="location.href='{% url 'guide:base' %}'">
                                <img src="{% static 'img/homemade.jpg' %}" style="display:block;"> 홈텐딩 길라잡이 시작하기
                                </button>
                        </td>
                        <td>
                                <button type="button" onclick="location.href='{% url 'guide:how' %}'">
                                <img src="{% static 'img/howtouse.png' %}" style="display:block;"> 길라잡이 활용하기
                                </button>
                        </td>
                </tr>
                <tr>

                </tr>
                <tr align="center">
                        <td>
                                <button type="button" onclick="location.href='{% url 'guide:info' %}'">
                                <img src="{% static 'img/otherinfo.jpg' %}" style="display:block;"> 그 밖의 정보들
                                </button>
                        </td>
                        <td>
                                <button type="button">
                                <img src="{% static 'img/bartending.jpg' %}" style="display:block;"> 나만의 칵테일 만들어보기
                                </button>
                        </td>
                </tr>
        </table>
        </div>
</div>
{% endblock %}

templates/guide/otherInfo.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h3>Other Information</h3>
<div class="container my-3">
        <div>
                <div style="font-size:18px; color:white;" align="center">
                        <p>이 페이지에서는 바텐딩과 관련된 다양한 정보를 얻을 수 있습니다.</p>
                        <p>간단한 칵테일이라도 더 맛있게 만들어 주는 도구와 방법들을 알아볼 수 있습니다.</p>
                </div>
        <table class="table">
                <tr align="center">
                        <td>
                                <button type="button" onclick="location.href='{% url 'guide:tool' %}'">
                                <img src="{% static 'img/tool.jpg' %}" style="display:block;">바텐딩 도구
                                </button>
                        </td>
                        <td>
                                <button type="button" onclick="location.href='{% url 'guide:term' %}'">
                                <img src="{% static 'img/bartending_term.jpeg' %}" style="display:block;">바텐딩 용어
                                </button>
                        </td>
                        <td>
                                <button type="button" onclick="location.href='{% url 'guide:source' %}'">
                                <img src="{% static 'img/source.png' %}" style="display:block;">출처
                                </button>
                        </td>
                </tr>
        </table>
        </div>
</div>
{% endblock %}

templates/guide/result.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<p>결과 화면</p>
<button type="button" onclick="location.href='{% url 'guide:index' %}'"> <!--/guide/second/-->
        기주페이지로 돌아가기
</button>

<img src="{% static 'img/screw_driver.jpg' %}" style="display:block;">스크류드라이버

{% endblock %}

templates/guide/secondAlchohol_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<p>보조주 화면</p>
<button class="favorite styled" type="button" name="orange" onclick="location.href='{% url 'guide:additives' %}'"> <!--/guide/second/-->
        <img src="{% static 'img/orange_juice.jpg' %}" style="display:block;">오렌지 주스
</button>
{% if }
<button class="favorite styled" type="button" name="cranberry" onclick="location.href='{% url 'guide:additives' %}'"> <!--/guide/second/-->
        <img src="{% static 'img/cranberry_juice.jpg' %}" style="display:block;">크랜베리 주스
</button>
{% endblock %}